"""
app_profile/export_targets.py — turn the application profile's code sources
into the registry file the indexer reads (`[[target]]` blocks, TOML).

    python -m app_profile.export_targets                 # writes indexer/targets.toml
    python -m app_profile.export_targets --out PATH      # writes PATH
    python -m app_profile.export_targets --stdout        # prints it

This is the hand-off between AppMind and the self-contained indexer: the
indexer imports nothing from AppMind, so the profile reaches it as a generated
file, not as a Python import. Re-run it whenever the profile changes (the
Docker setup does so on every `docker compose run indexer`). The output is
generated and git-ignored; never edit it by hand.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

from app_profile.loader import DEFAULT_SECRET, AppProfile, ProfileError
from app_profile.registry import PROJECT_ROOT, select_profile

DEFAULT_OUT = PROJECT_ROOT / "indexer" / "targets.toml"

HEADER = """\
# GENERATED by `python -m app_profile.export_targets` from the application
# profile (config/apps/{app_id}.yaml). Do not edit: change the profile and
# re-run the export. Identifiers only; no repository content.
"""


def _toml(value: str | list[str]) -> str:
    # A JSON string or array of strings is also a valid TOML basic string/array.
    return json.dumps(value, ensure_ascii=True)


def render_targets(profile: AppProfile) -> str:
    """The indexer's registry text for the profile's code sources."""
    blocks = [HEADER.format(app_id=profile.app.id)]
    for source in profile.sources.code:
        if source.secret != DEFAULT_SECRET:
            # The indexer reads one platform token (GITHUB_TOKEN). Exporting a
            # per-source secret it would ignore is a silent no-op, so refuse.
            raise ProfileError(
                f"sources.code {source.repo}: auth.secret {source.secret} is not supported by the indexer yet "
                f"(it only uses {DEFAULT_SECRET})"
            )
        blocks.append(
            "[[target]]\n"
            f"repo        = {_toml(source.repo)}\n"
            f"ref         = {_toml(source.ref)}\n"
            f"source_root = {_toml(source.source_root)}\n"
            f"exclude     = {_toml(list(source.exclude))}\n"
        )
    return "\n".join(blocks)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--out", type=pathlib.Path, default=DEFAULT_OUT, help=f"default: {DEFAULT_OUT}")
    parser.add_argument("--stdout", action="store_true", help="print instead of writing a file")
    args = parser.parse_args(argv)

    try:
        profile = select_profile()
        text = render_targets(profile)
    except ProfileError as exc:
        print(f"export_targets: {exc}", file=sys.stderr)
        return 1

    if args.stdout:
        print(text, end="")
        return 0
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8", newline="\n")
    print(f"[export_targets] wrote {len(profile.sources.code)} target(s) for {profile.app.id} to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
